// dependencies
const { text } = require('express');
const express = require('express');
const router = express.Router;
// npm package that creates 'random' ids 
const uuid = require('uuid');

// routing this file
module.exports = (app) => {
    // this get request reads the db file and then will return the saved notes in the db file as JSON objects
    app.get('/api/notes', (req, res) =>{
        res.sendFile(path.join(__dirname, '../db/db.json'));
    });

    // post request tacks the new note onto the db file 
    app.post('/api/notes', (req, res) => {
        // reads the db file before adding the new note
        const db = fs.readFileSync('db/db.json');
        db = JSON.parse(db);
        res.JSON(db);

        // note body 
        const note = {
            title: req.body.title,
            text: req.body.text,
            // random id for each note generated by the uuid npm package
            id: uuid(),
        }
        // push new note into the db file
        db.push(note);
        fs.writeFileSync('db/db.json', JSON.stringify(db));
        res.json(db)
    });

    // using the id from the note body, the delete request removes the user's desired notes
    app.delete('/api/notes/:id', (req, res) => {
        // reading the db file's notes
        const db = JSON.parse(fs.readFileSync('db/db/json'))
        // removes the note using .filter to 'search' for the note body's id 
        const delete = db.filter(item => item.id !== req.params.id);
        // rewriting the db file without the deleted note
        fs.writeFileSync('db/db.json', JSON.stringify(delete));
        res.json(delete);
    })
};